# pyproject.toml

[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
tag_regex = '^(?P<version>[0-9]+(?:\.[0-9]+)*)$'
